### ISSUE TITLE
GPL License declaration found in your code

### ISSUE THREAD

**Issue by titotarantula** [orbeon/tagsoup#2]
In the license declaration of class PYXScanner.java you declare the GPL 2.0 license applies for this file (among Apache 2.0). This is contradictory to the your declaration of Apache 2.0 to be applied on the software package since GPL 2.0 permissions and limitations also apply to the whole software package once it is used within your code. 

Please remove the notion of GPL 2.0 from the code or release the package under multi license  that allows the user to choose which license to apply. 

Thanks,
Alex

**Comment by ebruchez** [comment]
This was probably done by the original author of Tagsoup. Orbeon has not modified this file.

Generally, when files are licensed under multiple licenses, the user of the file gets to choose which applies. Orbeon chooses to interpret this file, and all files in that package as being under the Apache 2.0 license only. You, as a user, can make that same choice.

In any case, [this page](http://vrici.lojban.org/~cowan/XML/tagsoup/) clarifies the intent: "TagSoup is free and Open Source software. As of version 1.2, it is licensed under the Apache License, Version 2.0, which allows proprietary re-use as well as use with GPL 3.0 or GPL 2.0-or-later projects.".

**Comment by titotarantula** [comment]
Hi ebruchez,

thank you for clarifying. 
I just have two concerns on this: whatever is declared in the license declaration may be rendered invalid as soon as a more restrictive license (like GPL 2.0) is used somewhere in your code or any of your dependencies without. 
You are completely right when stating that a user may choose which license to apply when software is released under multiple licenses. However, it has to be made clear in the license declaration that this choice is possible, which is not the case in PYXScanner.java. 

Thanks to your comment, this is clear to me now.

br,
Alex
